lokahi/catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^acceptprivileges/(?P<uname>[\w\-]+)$', views.accept_privileges, name='accept_privileges'),

    url(r'^myreports/$', views.ReportsByUserListView.as_view(), name='my_reports'),
    url(r'^myreports/favorites/$', views.FavoritesByUserListView.as_view(), name='my_favorites'),
    url(r'^report/(?P<report_id>[0-9]+)$', views.report_detail, name='report_detail'),
    url(r'^report/(?P<report_id>[0-9]+)/favorite$', views.add_to_favorites, name='add_to_favorites'),
    url(r'^myreports/favorites/remove_from_favorites$', views.remove_from_favorites, name='remove_from_favorites'),
    url(r'^report/(?P<report_id>[0-9]+)/rate$', views.rate_report, name='rate_report'),
    url(r'^report/(?P<report_id>[0-9]+)/addfiles$', views.add_files, name='add_files'),
    url(r'^report/create$', views.create_report, name='create_report'),
    url(r'^report/encrypt/(?P<report_id>[0-9]+)$', views.encrypt_files, name='encrypt_files'),
    url(r'^report/edit/(?P<report_id>[0-9]+)$', views.edit_report, name='edit_report'),
    url(r'^report/edit/(?P<report_id>[0-9]+)/delete/(?P<file_id>[0-9]+)$', views.delete_file, name='delete_file'),
    url(r'^report/delete/(?P<report_id>[0-9]+)$', views.delete_report, name='delete_report'),
    url(r'^report/comments/(?P<report_id>[0-9]+)$', views.get_comments, name='report_comments'),
    url(r'^report/comments/create/(?P<report_id>[0-9]+)$', views.create_comment, name='create_comment'),

    url(r'^mymessages/$', views.MessagesByUserListView.as_view(), name='my_messages'),
    url(r'^message/(?P<message_id>[0-9]+)$', views.message_detail, name='message_detail'),
    url(r'^message/create$', views.create_message, name='create_message'),
    url(r'^message/delete/(?P<message_id>[0-9]+)$', views.delete_message, name='delete_message'),
    url(r'^message/download/(?P<message_id>[0-9]+)$', views.download_message, name='download_message'),
    url(r'^message/decrypt$', views.download_message, name='decrypt_message'),

    url(r'^mygroups/(?P<uname>[\w\-]+)$', views.my_groups, name='my_groups'),
    url(r'^group/create/(?P<user_id>[0-9]+)$', views.create_group, name='create_group'),
    url(r'^group/(?P<group_name>[0-9]+)$', views.group_detail, name='group_detail'),
    url(r'^group/(?P<group_name>[0-9]+)/remove/(?P<uname>[\w\-]+)$', views.remove_from_group, name='remove_from_group'),
    url(r'^group/(?P<group_name>[0-9]+)/add_user', views.add_user, name='add_user'),

    url(r'^signup/$', views.signup, name='signup'),
    url(r'^users/$', views.users, name='users'),
    url(r'^users/privileges/(?P<uname>[\w\-]+)$', views.privileges, name='privileges'),
    url(r'^suspend/(?P<uname>[\w\-]+)$', views.suspend, name='suspend'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search_messages/$', views.search_message, name='search_message'),
]

lokahi/lokahi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application
from django.conf.urls import include

urlpatterns += [
	url(r'^catalog/', include('catalog.urls')),
    url(r'^avatar/', include('avatar.urls')),
]

# Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
	url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True))
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    url(r'^logout/$', auth_views.logout, name='logout'),
]

lokahi/catalog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
from django.urls import reverse_lazy

class File(models.Model):
	file = models.FileField()
	report = models.CharField(max_length=200,default = 'none')
	encrypted = models.BooleanField(default=False)
	new = models.BooleanField(default = False)


class Report(models.Model):
	"""
	Model representing a report on LFC
	"""
	report_name = models.CharField(max_length=200, unique=True)
	company_name = models.CharField(max_length=40)
	company_phone = models.CharField(max_length=15)
	company_location = models.CharField(max_length=40)
	company_country = models.CharField(max_length=40)
	company_sector = models.CharField(max_length=40)
	company_industry = models.CharField(max_length=40)
	current_projects = 	models.TextField(help_text = "Enter a list of the current projects")
	info = models.TextField(help_text = "Enter information about the business plan and/or project")
	owner = models.CharField(max_length=50, default="admin")
	privacy_setting = models.CharField(max_length=10)
	timestamp = models.DateTimeField(auto_now_add = True)
	rating = models.IntegerField(default = 0)
	num_ratings = models.IntegerField(default = 0)
	hash_name = models.CharField(max_length=200)

	def __str__(self):
		return self.report_name

	def get_absolute_url(self):
		return reverse_lazy('report_detail', args=[str(self.id)])

	def get_edit_url(self):
		return reverse_lazy('edit_report', args=[str(self.id)])

	def get_delete_url(self):
		return reverse_lazy('delete_report', args=[str(self.id)])

	def get_comments_url(self):
		return reverse_lazy('report_comments', args=[str(self.id)])

	def create_comments_url(self):
		return reverse_lazy('create_comment', args=[str(self.id)])

class User(AbstractUser):
	"""
	Model representing a user of LFC
	"""
	username = models.CharField(max_length=200, default="none", unique=True)
	password = models.CharField(max_length=200, default="none")
	first_name = models.CharField(max_length=200, default="none")
	last_name = models.CharField(max_length=200, default="none")
	company = models.CharField(max_length=200, default="none")
	email = models.EmailField(max_length=200, default="none")
	user_type = models.CharField(max_length=10, default=1)
	is_suspended = models.BooleanField(default = False)
	public_key = models.TextField()
	has_manager_privileges = models.BooleanField(default = False)
	accepted_manager_privileges = models.BooleanField(default = False)
	favorites = models.ManyToManyField(Report)
	def __str__(self):
		return "%s" % (self.username)

class Comment(models.Model):
	"""
	Model representing a comment on a report
	"""
	report = models.ForeignKey(Report, related_name='comments')
	author = models.ForeignKey(User)
	text = models.TextField()

	def __str__(self):
		return "Comment by " + str(self.author)


# A user can leave a private message for a specific user. A user will have the ability to see a list of
# messages left for him or her, and be able to delete a message. Private messages will be encrypted, and
# the recipient can choose to decrypt it and then read

class Message(models.Model):
	"""
	Model representing a message between users
	"""

	recipient = models.ForeignKey(User, on_delete = models.CASCADE, related_name="recipient")
	sender = models.ForeignKey(User, on_delete= models.CASCADE,related_name="sender")
	message_body = models.TextField(help_text = "Enter your private message.")
	encrypted_message_body = models.BinaryField(default=b"")
	isItPrivate = models.BooleanField(default=True)
	is_encrypted = models.BooleanField(default=False)
	public_key = models.TextField()

	def __str__(self):
		return "Message " + str(self.is_encrypted)

	def get_absolute_url(self):
		return reverse_lazy('message_detail', args=[str(self.id)])

	def get_delete_url(self):
		return reverse_lazy('delete_message', args=[str(self.id)])

	def get_download_url(self):
		return reverse_lazy('download_message', args=[str(self.id)])

	def get_id(self):
		return str(self.id)


class Group(models.Model):
	"""
	Model representing groups that users can create
	"""
	users = models.CharField(max_length=200, default="")
	name = models.CharField(max_length=50, default="group", unique=True)
	reports = models.CharField(max_length=200, default="")
	# users = models.ManyToManyField(User)
	# group_reports = models.ManyToManyField(Report)
	#users = models.ManyToManyField(User)
	#reports = models.ManyToManyField(Report)

	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	# 	return reverse_lazy('group-detail', args=[str(self.name)])

lokahi/catalog/forms.py
from django import forms
from django.forms import ModelForm, Select
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.files.images import get_image_dimensions
from .models import User, Report
import datetime

class signUp(forms.Form):
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")
    company = forms.CharField(label="Company", required=False)
    username = forms.CharField(label="Username")
    email = forms.EmailField(label="E-mail")
    OPTIONS = (
        ('Investor',"Investor"),
        ('Company',"Company"),
        )
    user_type = forms.ChoiceField(choices=OPTIONS)
    password = forms.CharField(label="Password")


class CreateReportForm(forms.Form):
    report_name = forms.CharField(label="Report Name")
    company_name = forms.CharField()
    company_phone = forms.CharField()
    company_location = forms.CharField()
    company_country = forms.CharField()
    company_sector = forms.CharField()
    company_industry = forms.CharField()
    current_projects = forms.CharField(widget=forms.Textarea)
    info = forms.CharField(widget=forms.Textarea)
    filename = forms.FileField(label="Select a file", required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    OPTIONS = (
        ('Private',"Private"),
        ('Public',"Public"),
        )
    privacy_setting = forms.ChoiceField(choices=OPTIONS)
    owner = forms.CharField(label = "Owner (enter your username)")

class CreateCommentForm(forms.Form):
    author = forms.CharField(label = "Author (enter your own username)")
    text = forms.CharField()

class EditReportForm(forms.Form):
    company_name = forms.CharField(required=False)
    company_phone = forms.CharField(required=False)
    company_location = forms.CharField(required=False)
    company_country = forms.CharField(required=False)
    company_sector = forms.CharField(required=False)
    company_industry = forms.CharField(required=False)
    current_projects = forms.CharField(required=False, widget=forms.Textarea)
    info = forms.CharField(required=False, widget=forms.Textarea)
    filename = forms.FileField(label="Add files", required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))

class CreateMessageForm(forms.Form):
    recipient = forms.CharField()
    sender = forms.CharField()
    message_body = forms.CharField(widget=forms.Textarea)
    OPTIONS = (
        ('Private',"Private"),
        ('Public',"Public"),
        )
    privacy = forms.ChoiceField(choices=OPTIONS)
    OPTIONS = (
        ('Encrypted',"Encrypted  (only if private message)"),
        ('Unencrypted',"Unencrypted"),
        )
    encryption = forms.ChoiceField(choices=OPTIONS)

class DownloadMessageForm(forms.Form):
    private_key = forms.CharField(widget=forms.Textarea)

class CreateGroupForm(forms.Form):
    # public_reports = Report.objects.filter(privacy_setting = "Public")
    # users_reports = Report.objects.filter(owner = uname)
    group_name = forms.CharField()
    users = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=User.objects.all())
    # group_reports = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=self.merge)

    def __init__(self, *args, **kwargs):
        uname = kwargs.pop('uname')
        super(CreateGroupForm, self).__init__(*args, **kwargs)
        public_reports = Report.objects.filter(privacy_setting = "Public")
        users_reports = Report.objects.filter(owner = uname)
        merge = public_reports | users_reports
        self.fields['group_reports'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=merge)




class AddUserForm(forms.Form):
    user = forms.CharField()

class user_privileges(forms.Form):
    CHOICES = (
        ('False', "False"),
        ('True', "True"),
        )
    has_manager_privileges = forms.ChoiceField(CHOICES)

class searchForm(forms.Form):
    search = forms.CharField()

class searchMessageForm(forms.Form):
    search = forms.CharField()

class addFiles(forms.Form):
    filename = forms.FileField(label="Select files", widget=forms.ClearableFileInput(attrs={'multiple': True}))

lokahi/catalog/templates/catalog/detailedgroup.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Group: {{name}} </h1>
    <ul><b>Users:</b>
    	{% if user.user_type == "manager" %}
    	{% for u in users %}
      <li>
         {{u.username}} &nbsp; <a href="{% url 'remove_from_group' group_name=id uname=u.username%}" style ="font-size:0.85em">Remove from group</a>
      </li>
      	{% endfor %}
      	{% else %}
        {% for u in users %}
      <li>
         {{u.username }} &nbsp; {%if user.username == u.username%}<a href="{% url 'remove_from_group' group_name=id uname=u.username%}" style ="font-size:0.85em"> Leave group</a>{% endif %} 
      </li>
      	{% endfor %}
      	{% endif %}
        <br> <a href="{% url 'add_user' group_name=id%}">Add a user</a>
     </ul>
     <br> <ul><b>Reports:</b>
     	{% for r in reports %}
      <li>
         <a href="{{ r.get_absolute_url }}">{{ r.report_name }}</a>
      </li>
      	{% endfor %}
    </ul>
{% endblock %}

lokahi/catalog/templates/catalog/detailedmessage.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Message </h1>
    <ul>
      <li>
         Message: {{ message_body }}
      </li>
    </ul> 
    {% if user.is_authenticated and isItPrivate and is_encrypted and user.username == recipient.username %}
      <ul> <li> Encrypted message: {{ encrypted_message_body }} </li> </ul> <br>
    	<ul> <a href="{{ message.get_download_url }}"> Download your encrypted message </a> </ul> <br/>
    {% elif user.is_authenticated and isItPrivate and is_encrypted and not user.username == recipient.username %}
    	You cannot view this message as you are not the recipient of this encrypted private message. 
    {% elif not user.is_authenticated and isItPrivate and is_encrypted and user.username == recipient.username %}
    	Please authenticate to see this encrypted message
    {% endif %}

{% endblock %}

lokahi/catalog/templates/catalog/detailedreport.html
{% extends "base_generic.html" %}

{% block content %}
<head>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
    <h1>{{report_name}}</h1>
    <h2>Rating: {% if num_ratings == 0 %} no ratings {% elif current_rating == 1 %}<i class="fa fa-star"></i> {% elif current_rating == 2 %}<i class="fa fa-star"></i><i class="fa fa-star"></i> {% elif current_rating == 3 %} <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i> {% elif current_rating == 4 %}<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>{% else %}<i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>{% endif %} {% if user.username != owner %}
    <a href="{% url 'rate_report' report_id=id%}" style="font-size: 0.8em">Rate this report</a>{% endif %}</h2>
    <ul>
        <li>Owner: {{owner}}</li>
        <li>Company: {{company_name}}</li>
        <li>Phone #: {{company_phone}}</li>
        <li>Location: {{company_location}}</li>
        <li>Country: {{company_country}}</li>
        <li>Sector: {{company_sector}}</li>
        <li>Industry: {{company_industry}}</li>
        <li>Projects: {{current_projects}}</li>
        <li>Info: {{info}}</li>
        <li>Privacy: {{privacy_setting}}</li>
        <li>Files:
        {% if files.length != 0 %}
            <ul>
            {% for f in files %}
                {% if f.encrypted == False %}<li><a href="{{f.file.url}}">{{ f.file }}</a></li>
                {% else %}<li>{{ f.file }} (this file is encrypted and unavailable for download)</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}
        </li>
        <li>Date created: {{timestamp}}</li>
    </ul>
    <a href="{% url 'add_to_favorites' report_id=id%}">Favorite</a> <br/>
    {% if user.user_type == "Investor"%}
    <a href="{% url 'add_files' report_id=id%}">Add files</a><br/> {%endif%}
    <a href="{{ get_comments_url }}">Comments </a> <br/>
    <a href="{{ create_comments_url }}">Comment on this report</a>

    {% if user.user_type == 'manager' %}
    {% endif %}
{% endblock %}

lokahi/catalog/templates/catalog/list_comments.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Comments on this report </h1>

    {% for comment in comments %}
        <h2> Comment by: {{comment.author.username}} </h2>
        <p> &nbsp; &nbsp; {{comment.text}} </p>
    {% endfor %}
 
{% endblock %}

lokahi/catalog/templates/catalog/list_favorites.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Favorite Reports</h1>

    {% if user.favorites.all %}
      {% for report in user.favorites.all %}
      <li>
        <a href="{{ report.get_absolute_url }}">Name: {{report.report_name}}</a>,
         Company: {{report.company_name}},
         Privacy: {{report.privacy_setting}}<br/>
         <a href="{{ report.get_edit_url }}" style="margin-left:1em">Edit this report</a>,
         <a href="{{ report.get_delete_url }}">Delete this report</a>,
         <a href="{{ report.get_comments_url }}"> Comments </a>
      </li>
      {% endfor %}

    {% else %}

      <p>There are no reports.</p>
    {% endif %}
{% endblock %}

lokahi/catalog/templates/catalog/list_groups.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Groups</h1>

    {% if user.is_authenticated %}
    <a href="{% url 'create_group' user_id=user.id %}">Create A Group</a>
    {% endif %}

    {% if list_groups %}
    <ul>
      {% for group in list_groups %}
      <li>
        <h4> Group name: {{ group.name }} </h4>
        <a href="{% url 'group_detail' group_name=group.id%}"> Click for details </a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no groups.</p>
    {% endif %}

{% endblock %}

lokahi/catalog/templates/catalog/list_message_results.html
{% extends "base_generic.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en-US">
<head>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
<h1> Search Results for {{ search }}</h1>
    {% for m in messages %}
        <li>
          <a href="{{ m.get_absolute_url }}"> Recipient: {{m.recipient.username}} </a>
        </li>
    {% endfor %}
</body>
</html>
{% endblock %}

lokahi/catalog/templates/catalog/list_messages.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Messages</h1>

    {% if user.is_authenticated %}
    <a href="{% url 'create_message'%}">Create A Message</a>
    {% endif %}

    {% if message_list %}
    <ul>
      <h2>Received</h2> 
      {% for message in message_list %}
          {% if user.username == message.recipient.username %}

        <h3>Message</h3>
          <li>
            Recipient: {{ message.recipient.username }}
          </li>
          <li>
             <a href="{{ message.get_absolute_url }}"> Click to see message </a>
          </li>
          <li>
              Private? {{ message.isItPrivate }}
          </li>
          <li>
          {% if message.isItPrivate == True %}
          <a href="{{ message.get_delete_url }}">Click to delete your private message</a>
          {% endif %}
          <li>
          {% endif %}

      {% endfor %}
     <h2>Sent</h2> 
      {% for message in message_list %}
          {% if user.username == message.sender.username %}

        <h3>Message to {{ message.recipient.first_name }} {{ message.recipient.last_name }}</h3>
          <li>
            Recipient: {{ message.recipient.username }}
          </li>
          <li>
             <a href="{{ message.get_absolute_url }}"> Click to see message </a>
          </li>
          <li>
              Private? {{ message.isItPrivate }}
          </li>
          {% endif %}

      {% endfor %}
    </ul>
    {% else %}
      <p>There are no messages.</p>
    {% endif %}
 
{% endblock %}

lokahi/catalog/templates/catalog/list_reports.html
{% extends "base_generic.html" %}

{% block content %}
    {% if user.is_authenticated and user.user_type == 'Company'%}
      <h1>My Reports</h1>
    {% elif user.user_type == 'Investor' or user.user_type == 'manager'%}
      <h1>All Reports</h1>
    {% endif %}
    <a href="{% url 'my_favorites' %}">Favorites</a>
    {% if report_list %}

    <ul>

      {% if user.user_type == "manager" or user.accepted_manager_privileges %}

        {% for report in report_list %}
        <li>
          <a href="{{ report.get_absolute_url }}">Name: {{report.report_name}}</a>,
           Company: {{report.company_name}},
           Privacy: {{report.privacy_setting}}<br/>
           <a href="{{ report.get_edit_url }}" style="margin-left:1em">Edit this report</a>,
           <a href="{{ report.get_delete_url }}">Delete this report</a>,
           <a href="{{ report.get_comments_url }}"> Comments </a>
        </li>
        {% endfor %}
      {% elif user.user_type == 'Investor' %}

        {% for report in report_list %}
        {% if report.privacy_setting == 'Public' %}
        <li>
          <a href="{{ report.get_absolute_url }}">Name: {{report.report_name}}</a>,
           Company: {{report.company_name}},
           Privacy: {{report.privacy_setting}}<br/>
           <a href="{{ report.get_comments_url }}"> Comments </a>

        </li>
        {% endif %}
        {% endfor %}
      {% else %}
        <!--Company users can view all reports that they created (public or private)-->        
        <form action="{% url 'my_reports' %}" method="get">

        {% for report in report_list %}
        {% if user.username == report.owner or report.privacy_setting == 'Public' %}
          <li>
            <a href="{{ report.get_absolute_url }}">Name: {{report.report_name}}</a>,
             Company: {{report.company_name}},
             Privacy: {{report.privacy_setting}},
             <a href="{{ report.get_edit_url }}">Edit report</a>,
             <a href="{{ report.get_comments_url }}"> Comments </a>
        {% endif %}
        {% endfor %}
      {% endif %}
    </ul>

    <h4>
      To edit a report, click on the link at the end of the report preview and change the fields that need to be changed.
      For fields that should stay the same, copy and paste the old content back into the form. Report name, report owner, and privacy
      cannot be updated.
    </h4>

    {% else %}

      <p>There are no reports.</p>
    {% endif %}
    {% if user.user_type == 'Company' %}
      <a href="{% url 'create_report'%}">Create A Report</a>
    {% endif %}
{% endblock %}

lokahi/catalog/templates/catalog/list_results.html
{% extends "base_generic.html" %}

{% block content %}
<!DOCTYPE html>
<html lang="en-US">
<head>
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
<h1> Search Results for {{ search }}</h1>
    {% for r in reports %}
        {% if r.privacy_setting == "Public" %}
        <li>
          <a href="{{ r.get_absolute_url }}"> Name: {{r.report_name}} </a>
        </li>
        {% endif %}
    {% endfor %}
</body>
</html>
{% endblock %}